function Hd = ButterworthProbando
%BUTTERWORTHPROBANDO Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 16-Aug-2023 12:11:52

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

N   = 6;     % Order
Fc1 = 500;   % First Cutoff Frequency
Fc2 = 1500;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
